import fs from "node:fs";
import { ConfigStore } from "../config/config-store";
import { expandTilde } from "@/utils/platform";
import { sanitizeConfigString } from "@/utils/security";

export class SshConfigGenerator {
  private store: ConfigStore;

  constructor(store: ConfigStore) {
    this.store = store;
  }

  generate(): string {
    this.store.ensureDirectories();
    const accounts = this.store.loadAccounts();
    const paths = this.store.getPathResolver();
    const generatedSshFile = paths.getGeneratedSshConfigFile();

    let content = `# Auto-generated by GitBridge. DO NOT EDIT DIRECTLY.\n`;
    content += `# Generated at: ${new Date().toISOString()}\n\n`;

    // Filter accounts with SSH key configured
    const sshAccounts = accounts.filter((a) => a.sshKeyPath);

    if (sshAccounts.length === 0) {
      content += `# No accounts currently configured with custom SSH keys.\n`;
    } else {
      for (const account of sshAccounts) {
        const cleanHost = sanitizeConfigString(account.host);
        const cleanId = sanitizeConfigString(account.id);
        const hostAlias = `${cleanHost}-${cleanId}`;
        const keyPath = sanitizeConfigString(expandTilde(account.sshKeyPath!));
        const cleanUser = "git";
        const displayName = sanitizeConfigString(account.displayName || account.username);

        content += `# Account: ${displayName} (${account.providerId})\n`;
        content += `Host ${hostAlias}\n`;
        content += `    HostName ${cleanHost}\n`;
        content += `    User ${cleanUser}\n`;
        if (account.sshPort && typeof account.sshPort === "number" && account.sshPort > 0 && account.sshPort < 65536) {
          content += `    Port ${account.sshPort}\n`;
        }
        content += `    IdentityFile "${keyPath}"\n`;
        content += `    IdentitiesOnly yes\n\n`;
      }
    }

    fs.writeFileSync(generatedSshFile, content, { encoding: "utf-8", mode: 0o600 });
    try {
      fs.chmodSync(generatedSshFile, 0o600);
    } catch {
      // ignore on Windows
    }
    return generatedSshFile;
  }
}
