import fs from "node:fs";
import { ConfigStore } from "../config/config-store";
import { expandTilde } from "@/utils/platform";
import { sanitizeConfigString } from "@/utils/security";

export class GitConfigGenerator {
  private store: ConfigStore;

  constructor(store: ConfigStore) {
    this.store = store;
  }

  /**
   * Generates all Git configuration files into ~/.gitbridge/generated/
   */
  generate(): { mainConfigPath: string; generatedRules: string[] } {
    this.store.ensureDirectories();
    const config = this.store.loadConfig();
    const identities = this.store.loadIdentities();
    const accounts = this.store.loadAccounts();
    const paths = this.store.getPathResolver();

    const defaultIdentity = identities.find((i) => i.id === config.defaultIdentityId) || identities.find((i) => i.isDefault) || identities[0];

    const ruleFiles: string[] = [];

    // 1. Generate individual rule files
    for (const rule of config.rules) {
      const ruleIdentity = identities.find((i) => i.id === rule.identityId);
      const ruleFile = paths.getRuleGitConfigFile(rule.id);

      const cleanRuleId = sanitizeConfigString(rule.id);
      let ruleContent = `# Managed by GitBridge for rule: ${cleanRuleId}\n`;
      if (ruleIdentity) {
        const cleanName = sanitizeConfigString(ruleIdentity.name);
        const cleanEmail = sanitizeConfigString(ruleIdentity.email);
        ruleContent += `[user]\n`;
        ruleContent += `    name = ${cleanName}\n`;
        ruleContent += `    email = ${cleanEmail}\n`;
        if (ruleIdentity.signingKey) {
          const cleanKey = sanitizeConfigString(ruleIdentity.signingKey);
          ruleContent += `    signingkey = ${cleanKey}\n`;
          ruleContent += `    # format = ssh or gpg\n`;
        }
      }

      // Check if rule specifies an account with SSH rewrite
      if (rule.defaultAccountId) {
        const account = accounts.find((a) => a.id === rule.defaultAccountId);
        if (account && account.host) {
          const cleanHost = sanitizeConfigString(account.host);
          const cleanId = sanitizeConfigString(account.id);
          const aliasHost = `${cleanHost}-${cleanId}`;
          ruleContent += `\n[url "git@${aliasHost}:"]\n`;
          ruleContent += `    insteadOf = git@${cleanHost}:\n`;
          if (account.sshPort && account.sshPort !== 22) {
            ruleContent += `    insteadOf = ssh://git@${cleanHost}:${account.sshPort}/\n`;
          }
          ruleContent += `    insteadOf = ssh://git@${cleanHost}/\n`;
        }
      }

      fs.writeFileSync(ruleFile, ruleContent, { encoding: "utf-8", mode: 0o600 });
      try {
        fs.chmodSync(ruleFile, 0o600);
      } catch {
        // ignore on Windows
      }
      ruleFiles.push(ruleFile);
    }

    // 2. Generate main.gitconfig
    let mainContent = `# Auto-generated by GitBridge. DO NOT EDIT DIRECTLY.\n`;
    mainContent += `# Generated at: ${new Date().toISOString()}\n\n`;

    if (defaultIdentity) {
      const cleanName = sanitizeConfigString(defaultIdentity.name);
      const cleanEmail = sanitizeConfigString(defaultIdentity.email);
      mainContent += `# Default Identity\n`;
      mainContent += `[user]\n`;
      mainContent += `    name = ${cleanName}\n`;
      mainContent += `    email = ${cleanEmail}\n`;
      if (defaultIdentity.signingKey) {
        const cleanKey = sanitizeConfigString(defaultIdentity.signingKey);
        mainContent += `    signingkey = ${cleanKey}\n`;
      }
      mainContent += `\n`;
    }

    if (config.settings.credentialHelperEnabled) {
      mainContent += `# Git Credential Helper Bridge\n`;
      mainContent += `[credential]\n`;
      mainContent += `    helper = gitbridge credential\n\n`;
    }

    if (config.rules.length > 0) {
      mainContent += `# Directory-Based Conditional Includes\n`;
      for (const rule of config.rules) {
        const ruleFile = paths.getRuleGitConfigFile(rule.id);
        const cleanRulePath = sanitizeConfigString(rule.path);
        const expandedRulePath = expandTilde(cleanRulePath);
        // gitdir format requires trailing slash for directories
        const gitDirPattern = expandedRulePath.endsWith("/") ? `${expandedRulePath}**` : `${expandedRulePath}/**`;
        mainContent += `[includeIf "gitdir:${gitDirPattern}"]\n`;
        mainContent += `    path = ${ruleFile}\n\n`;
      }
    }

    const mainFile = paths.getMainGitConfigFile();
    fs.writeFileSync(mainFile, mainContent, { encoding: "utf-8", mode: 0o600 });
    try {
      fs.chmodSync(mainFile, 0o600);
    } catch {
      // ignore on Windows
    }

    return {
      mainConfigPath: mainFile,
      generatedRules: ruleFiles,
    };
  }
}
